@startuml nama
start

:Display "===== MENU =====";
:Display "1. Makanan";
:Display "2. Minuman";
:Display "3. Keluar";
:Input pilihan;

while (pilihan != 3) is (true)
    if (pilihan == 1) then (yes)
        :Display "===== MENU MAKANAN =====";
        :Display "1. Pecel Lele (Rp. 15000)";
        :Display "2. Nasi Goreng (Rp. 20000)";
        :Display "3. Kembali";
        :Input makanan;
        
        if (makanan == 1) then (yes)
            :Display "Anda memilih Pecel Lele. Harga: Rp. 15000";
        else (no)
            if (makanan == 2) then (yes)
                :Display "Anda memilih Nasi Goreng. Harga: Rp. 20000";
            else (no)
                if (makanan == 3) then (yes)
                    :Go to main menu;
                else (no)
                    :Display "Pilihan tidak valid!";
                endif
            endif
        endif
    else (no)
        if (pilihan == 2) then (yes)
            :Display "===== MENU MINUMAN =====";
            :Display "1. Es Teh (Rp. 5000)";
            :Display "2. Kopi (Rp. 10000)";
            :Display "3. Kembali";
            :Input makanan;

            if (makanan == 1) then (yes)
                :Display "Anda memilih Es Teh. Harga: Rp. 5000";
            else (no)
                if (makanan == 2) then (yes)
                    :Display "Anda memilih Kopi. Harga: Rp. 10000";
                else (no)
                    if (makanan == 3) then (yes)
                        :Go to main menu;
                    else (no)
                        :Display "Pilihan tidak valid!";
                    endif
                endif
            endif
        else (no)
            :Display "Pilihan tidak valid!";
        endif
    endif
    :Display "===== MENU =====";
    :Display "1. Makanan";
    :Display "2. Minuman";
    :Display "3. Keluar";
    :Input pilihan;
endwhile (false)

:Display "Terima kasih!";
stop
@enduml