@startuml name
skinparam backgroundColor #ffffff
skinparam node {
    BorderColor #000000
    BorderThickness 2
    BackgroundColor #ffffff
}
skinparam arrow {
    BorderColor #000000
    BorderThickness 2
}

package "My App" {
    :Home(Home): --> [Review]
    :Review --> [Edit]
    :Review --> Help
    :Edit( Edit): --> [(Database) Submit]
    [(Database) Submit] --> Review
}
@enduml